<a href="https://colab.research.google.com/github/taiye-official/DSN-Class-exercises/blob/master/DSN_Class_on_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Importing numpy
import numpy as np

In [2]:
#Creating array with the np.arange method
arr_n = np.arange (0,20)
arr_n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
#Creating array from a list
my_list = list (range (0,10))
arr_from_list = np.array (my_list)
arr_from_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Array attributes

In [4]:
#Finding out the shape of vector arr_n
arr_n.shape

(20,)

In [5]:
#Reshaping Matrix arr_n to a 5 x 4 matrix
arr_n.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
#Reshaping Matrix arr_n to a 4 x 5 matrix
arr_n.reshape (4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
#finding out the data type of the object in the array; arr_n
arr_n.dtype

dtype('int64')

Array Methods

In [8]:
#Using the np.zeros to create an array of all zeroes
np.zeros (3)


array([0., 0., 0.])

In [9]:
np.zeros (6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#Using the np.ones to create an array of all ones
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#Using the linspace method to create an array of evenly spaced numbers
# (0,10, 5) = 0 is the start point, 10 is the stop point and 5 is the number of values you want
np.linspace (0,10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
#Using the arange method to create an array of evenly spaced numbers
# (0,10, 5) = 0 is the start point, 10 is the stop point and 1 is the number of steps or intervals between values
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Using the eye method to create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#Extra Stuff for Beginners
#(5,2,1) = 5 is the number of rows, 4 is the number of columns and 1 is the diagonal you want your ones to be (+ value = up, - value = lower)
np.eye(5,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#Generating random samples with the random.rand method
np.random.rand(4,3)

array([[0.9728416 , 0.55912239, 0.29040701],
       [0.03505726, 0.17282851, 0.08679949],
       [0.7579327 , 0.49808082, 0.76713909],
       [0.82071206, 0.2042892 , 0.96755606]])

In [19]:
#Generating random integers with the random.randint method
np.random.randint(4,20)

19

In [20]:
np.random.randint(4,20,5)

array([16, 17, 11,  7, 13])

Array Indexing and Slicing

In [21]:
#Indexing
arr_n[4]

4

In [22]:
arr_n[0]

0

In [23]:
#Slicing
arr_n[2:5]

array([2, 3, 4])

In [24]:
arr_n[0:(len(arr_n)):2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
#Broadcasting
arr_n[0:5] = 34
arr_n

array([34, 34, 34, 34, 34,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
arr_n = arr_n + 10
arr_n

array([44, 44, 44, 44, 44, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [27]:
arr_o = arr_n.reshape(5, 4)
arr_o

array([[44, 44, 44, 44],
       [44, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [28]:
#Indexing rows
arr_o[2]

array([18, 19, 20, 21])

In [29]:
#Indexing columns
arr_o[:2]

array([[44, 44, 44, 44],
       [44, 15, 16, 17]])

In [30]:
#Getting individual element
arr_o[2,2]

20

In [31]:
# OR Getting individual element
arr_o[2][2]

20

In [32]:
#Slicing
arr_o[0:3,2:4]

array([[44, 44],
       [16, 17],
       [20, 21]])

In [33]:
#Selection
bool_arr = arr_o < 20
bool_arr

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
arr_o[bool_arr]

array([15, 16, 17, 18, 19])

In [35]:
arr_o[arr_o >20]

array([44, 44, 44, 44, 44, 21, 22, 23, 24, 25, 26, 27, 28, 29])

Array Operations

In [36]:
#minimum value in the array, arr_n
arr_n.min()

15

In [37]:
#maximum value in the array, arr_n
arr_n.max()

44

In [38]:
#Addition
arr_o + arr_o

array([[88, 88, 88, 88],
       [88, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [39]:
#Subtraction
arr_o - arr_o

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
#Multiplication
arr_o * arr_o

array([[1936, 1936, 1936, 1936],
       [1936,  225,  256,  289],
       [ 324,  361,  400,  441],
       [ 484,  529,  576,  625],
       [ 676,  729,  784,  841]])

In [41]:
#Vector Multiplication
arr_o @ arr_o.reshape(4,5)

array([[4576, 4708, 4840, 4972, 5104],
       [2906, 2954, 3002, 3050, 3098],
       [2002, 2062, 2122, 2182, 2242],
       [2418, 2490, 2562, 2634, 2706],
       [2834, 2918, 3002, 3086, 3170]])

In [42]:
# using sum function
arr_o.sum()

550

In [43]:
# finding standard deviation of the elements in the array
arr_o.std()

10.23474474522936

Other operations include; exponential, squares, square roots, trigonometry.